<a href="https://colab.research.google.com/github/MrGyani/Scientific-Computation/blob/main/Lab1_Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1><center>Computer lab 1: Introduction to numpy and matplotlib</center></h1>
<h2><center>Part 1: Vectors and matrices</center></h2>

<p><b>Numpy</b> is a fundamental package for scientific computations with Python. It offers a large number of numerical computing tools, for example mathematical functions, random number generators, arrays of different dimensions, linear algebra tools etc. In this part of the lab we will focus on arrays in 1D (also called vectors) and in 2D (also called matrices).</p>
<h3>Instructions</h3>
<p>As you can see there are a number of cells (grey boxes) below, and in some cells there will be code. You run the code in the currect cell by clicking the <b>Run</b>-button. In other cases you are asked to add code into particular a cell yourself. You add the code, and run the cell. If it does not work, update and run it again, until it works. In this way, the labs will be a mix of running existing code and doing a bit of coding yourself. Try to understand the results you get and what you are doing, and ask if you don't understand.</p>
<hr>
<h3>Import the numpy library</h3>
<p>First, in order to use <b>numpy</b> you need to import it. By convention, "np" is used as a shortened name.</p>

In [1]:
import numpy as np

<h3>Defining vectors and matrices</h3>
<p>Run the cell below, to define two vectors (or 1D-arrays), $x$ and $y$. To do that, we use <b>numpy</b>'s <code>np.array</code> function. We also display the vectors on the screen, so you can see what they look like.</p>

In [2]:
x = np.array([1, 2, 3])
y = np.array([[4],[5],[6]])
print('x = ',x)
print('y =\n',y)

x =  [1 2 3]
y =
 [[4]
 [5]
 [6]]


<p>What <code>np.array</code> does is to convert a list (a datatype in Python) to an array. The list in the first case is <tt>[1, 2, 3]</tt>. We can also use nested lists (a list in a list) as in the case with vector $y$. The inner list (here <tt>[4]</tt>, <tt>[5]</tt> and <tt>[6]</tt>) will represent each row in the array. This will generate a column vector.
<p>A couple of often used and practical functions are <code>shape</code> and <code>size</code>. Run the cell to see what they result in.</p>

In [3]:
print(np.shape(y))
print(np.size(y))

(3, 1)
3


The first output here is a tuple, and gives us information about the number of rows (=3) and the number of columns (=1). The second output (<code>size</code>) tells us the number of elements in the array.<br><br>
Alternatively, you can write the commands like <code>y.shape</code>. Try it in the cell below!

In [8]:
# Enter your code here
y.shape


(3, 1)

<p>Now, if $y$ is $3 \times 1$, then $x$ must be $1 \times 3$? Check this out by displaying the shape of $x$:</p>

In [7]:
# Enter your code here
x.shape

(3,)

<p>Apparently $x$ isn't $1 \times 3$, as the result is <tt>(3,)</tt>. It is actually considered neither a column vector or a row vector. <br>
    We can investigate the dimensions of $x$ and $y$, using <code>ndim</code>: </p>

In [10]:
print(np.ndim(x))
print(np.ndim(y))

1
2


As you can see $x$ is considered to be of dimension 1, whereas $y$ is of dimension 2 (three rows and one column), which technically is a matrix. If you need a 2-dimensional <i>row vector</i>, you can use double brackets, like <code>z = np.array([[1, 2, 3]])</code>:

In [11]:
z = np.array([[1, 2, 3]])
print('z = ', z)
print('Shape: ', z.shape)
print('Dimension: ',z.ndim)

z =  [[1 2 3]]
Shape:  (1, 3)
Dimension:  2


<p>This would create a 2D-array with 1 row and 3 columns. </p>
<p>Generally, the norm is 1D for vectors, and you don't really keep row and column vector differentiated in <b>NumPy</b>. However, in a linear algebra context there might be cases where you want to distinguish between row and column vectors, and it's therefore good to be aware of this. <b>Numpy</b> will often automatically reshape 1D vectors to a 2D shape in operations where 2D arrays are involved. How <b>numpy</b> treat arrays with different shapes during arithmetic operations is called 'broadcasting', and if you are interested you can read more about it here: <a href="https://numpy.org/doc/stable/user/basics.broadcasting.html" target="_blank">https://numpy.org/doc/stable/user/basics.broadcasting.html</a></p>
<hr>
<p>&nbsp;</p>
<h4>Matrices in numpy</h4>
<p>Matrices are created in the same way as you created $y$, i.e. inner brackets generates rows. Try to create the two matrices
$$ \begin{array}{ll}
A = \left( \begin{array}{ccc}
2 & 4 & -6 \\
1 & 5 & 3 \\
1 & 3 & 2
\end{array} \right) \; \; \mbox{ and} &
B = \left( \begin{array}{cc}
1 & 2 \\
3 & 4 \\
5 & 6
\end{array}\right)
\end{array}
$$
Also, print the matrices on the screen to check that they look correct.</p>

In [15]:
# Enter your code here
A=np.array([[2,4,-6],[1,5,3],[1,3,2]])
B=np.array([[1,2],[3,4],[5,6]])
print(np.size(A))
print(np.shape(A))
print(np.size(B))
print(np.shape(B))

9
(3, 3)
6
(3, 2)


<p>To be really sure they are correct, also check the shape, dimension and size of the matrices:</p>

In [17]:
# Enter your code here
print(A.ndim)
print(B.ndim)

2
2


<h3>Accessing elements in vectors and matrices</h3>
<p>Each element in an array has an index to indicate the location: <code>x[i]</code> would get the element in location <tt>i</tt>. As the first index in numpy is always 0, it means that <code>x[i]</code> is equal to $x_{i+1}$ in 'mathematical' notation (in 'mathematical' notation indexing is usually $x_1, x_2, \ldots$, i.e. starting at index 1).</p>
<p>Print the first and the last element in $x$ on the screen. To se if it is correct, compare with the vector $x$.</p>

In [23]:
# Enter your code here
print(A)
print(A[0])


[[ 2  4 -6]
 [ 1  5  3]
 [ 1  3  2]]
[ 2  4 -6]
[1 3 2]


<p>
Remember, the first element $x_1$ is located in index 0 (<code>x[0]</code>). <br>
<br>The last element in a vector can also be accessed using index <code>-1</code>. Try it!
    </p>

In [24]:
# Enter your code
print(A[-1])

[1 3 2]


<p>This is practical to use when you work with big vectors/matrices and it hard to know the number of elements. We can of course find the number of elements, but it is easier to just use index <code>-1</code>.</p>
<p>What about matrices? A 2D-array have two indices, row-index and column-index, and <code>A[i,j]</code> would access element $(i,j)$.<br>
Try to display
    <ul>
    <li>the element in $A_{11}$, i.e. the upper left element in $A$  (remember index start at 0 in Python)</li>
    <li>the element in $A_{23}$</li>
    <li>the element in the last row and last column in $B$ (remember <code>-1</code> gives the last element.)</li>
        </ul>
   Check that you actually displayed the correct element on the screen by comparing with $A$!
        </p>

In [28]:
# Enter your code here
print(A)
print(A[0,0])
print(A[1,2])
print(A[-1,-1])

[[ 2  4 -6]
 [ 1  5  3]
 [ 1  3  2]]
2
3
2


<p>
    What happens if you by mistake try to access an element outside the array boundaries? Try to display element $B_{41}$ (again, remember index begin at 0 in Python)</p>

In [29]:
# Enter your code here
print(B[4,1])

IndexError: index 4 is out of bounds for axis 0 with size 3

<p>
As you can see, Python tells you that your index (index number 3) is out of bounds for 'axis 0'. Axes are defined for arrays with dimension 2 (or higher), and 'axis 0' corresponds the elements running vertically, i.e. the columns, and 'axis 1' corresponds elements running horizontally, i.e. the rows.<br>
Trying to access element outside the array bounds is quite a common mistake, and it is therefore good to quickly be able to interpret this error message.
    </p>

<p>You can of course also change a specific element in vectors/matrices, by just assigning a value to a specific index. For example <code>A[1,2] = 0</code> would change element $(2,3)$ in $A$ to a zero.<br> Do this change, and also print $A$ on the screen to be sure you changed the correct index!

In [30]:
# Enter your code here
print(A)
A[1,2]=0
print(A)

[[ 2  4 -6]
 [ 1  5  3]
 [ 1  3  2]]
[[ 2  4 -6]
 [ 1  5  0]
 [ 1  3  2]]


<h4>The colon operator</h4>
<p>It is often the case that we would like to index a range of elements at the same time. That can be done using the colon (<code>:</code>) operator. <br>
Run the code below, compare the results with $x$ and $A$, and try to understand how the colon operator works.

In [31]:
print('First we display x and A')
print('x = ', x)
print('A = \n', A)
print('--')
print('Compare the results with x and A above. Try to understand how \':\' works.')
print('x[0:2] => ', x[0:2])
print('x[:2]  => ', x[:2])
print('x[1:]  => ', x[1:])
print('A[1:,0:2] => \n', A[1:,0:2])

First we display x and A
x =  [1 2 3]
A = 
 [[ 2  4 -6]
 [ 1  5  0]
 [ 1  3  2]]
--
Compare the results with x and A above. Try to understand how ':' works.
x[0:2] =>  [1 2]
x[:2]  =>  [1 2]
x[1:]  =>  [2 3]
A[1:,0:2] => 
 [[1 5]
 [1 3]]


<p> Index <code>a:b</code> result in all elements starting from <code>a</code> and number of elements <code>b</code>. If any of <code>a</code> or <code>b</code> are unspecified we mean from the first element and/or to the dimension size, respectively. You can also see in the last example that the colon operator can be used to access submatrices. In this case the rows from index 1 to the end, and the columns from index 0 to column number 2.</p>
<p>
Try on your own to

*   Display (on the screen) the last row of $A$
*   Display the 2nd column of $A$
*   Change the first row of $A$ to [1 2 3] (use only one command)
*   Create a matrix $C$ equal to the $2 \times 2$ upper right corner of $A$

Check that you actually displayed the correct element on the screen!
        </p>

In [46]:
# Enter your code here
print(A)
print('last row of A: ', A[2,])
n=np.array([A[0:,2]])
n=np.transpose(n)
print('2nd Column of A: \n', n)

[[ 2  4 -6]
 [ 1  5  0]
 [ 1  3  2]]
last row of A:  [1 3 2]
2nd Column of A: 
 [[-6]
 [ 0]
 [ 2]]


<h4>Arrays in arithmetic functions</h4>
<p>Numpy has many arithmetic functions, such as <code>sin</code>, <code>cos</code>, <code>sqrt</code> etc., that can take arrays as input arguments. The function is evaluated elementwise, i.e. for every element in the array.</p>
<p>Try <code>np.sqrt(B)</code>, <code>np.cos(B)</code>. Also try <code>B**2</code> and <code>B**3</code> (<code>**</code> means 'elementwise power to'). Compare the results with $B$.</p>

In [48]:
# Enter your code here
print('Square root of B: ', np.sqrt(B))
print('cosine of B: ', np.cos(B))
print('Sine of B: ', np.sin(B))
print('Tangent of B: ', np.tan(B))
print('Square of B: ', B**2)
print('Cube of B: ', B**3)

Square root of B:  [[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]
cosine of B:  [[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]
 [ 0.28366219  0.96017029]]
Sine of B:  [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155 ]]
Tangent of B:  [[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]
 [-3.38051501 -0.29100619]]
Square of B:  [[ 1  4]
 [ 9 16]
 [25 36]]
Cube of B:  [[  1   8]
 [ 27  64]
 [125 216]]


<p>To use vectors in arithmetic functions is often a way to suppress for-loops. Working on whole arrays in <b>numpy</b>, rather than element by element in a loop is both esier and also faster.
<p>We will look at other operations such as matrix multiplication, addition/subtraction etc. in part 3 of this lab. Now, continue with part 2...</p>
<p><hr></p>